import { StyleSheet } from "react-native";
import {
  mobileColors,
  mobileRadius,
  mobileSpacing,
  mobileTypography,
} from "./mobileTokens";

export const analysisStyles = StyleSheet.create({
  analysisResultStack: {
    gap: 24,
  },
  chunkContent: {
    maxWidth: "100%",
    minWidth: 0,
    position: "relative",
  },
  chunkEnglish: {
    color: mobileColors.ink,
    fontSize: 20,
    fontWeight: "900",
    lineHeight: mobileTypography.lineHeight.lg,
  },
  chunkEnglishLine: {
    alignItems: "baseline",
    flexDirection: "row",
    flexWrap: "wrap",
    maxWidth: "100%",
    minWidth: 0,
  },
  chunkSlash: {
    color: mobileColors.accent,
    fontSize: 24,
    fontWeight: "900",
    lineHeight: 31,
    marginHorizontal: 2,
  },
  chunkUnit: {
    alignItems: "flex-start",
    flexShrink: 1,
    maxWidth: "100%",
    minWidth: 0,
  },
  chunkUnitActive: {
    zIndex: 30,
  },
  chunkKorean: {
    color: mobileColors.inkMuted,
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 19,
  },
  chunkLine: {
    alignItems: "flex-start",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    minWidth: 0,
    width: "100%",
  },
  grammarExplanation: {
    color: mobileColors.inkMuted,
    fontSize: 13,
    lineHeight: 20,
    minWidth: 0,
  },
  grammarDescription: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    minWidth: 0,
  },
  grammarItem: {
    alignItems: "baseline",
    flexDirection: "row",
    gap: 12,
    minWidth: 0,
  },
  grammarList: {
    gap: 10,
  },
  grammarTarget: {
    color: mobileColors.ink,
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 20,
    minWidth: 0,
  },
  grammarType: {
    color: mobileColors.inkMuted,
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 20,
  },
  noteItem: {
    gap: mobileSpacing.xs,
  },
  noteTerm: {
    color: mobileColors.primary,
    fontSize: mobileTypography.size.sm,
    fontWeight: "800",
    lineHeight: 20,
  },
  noteText: {
    color: mobileColors.ink,
    fontSize: mobileTypography.size.sm,
    lineHeight: 23,
  },
  resultArea: {
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    gap: 0,
    overflow: "hidden",
    padding: 0,
  },
  sourceSample: {
    backgroundColor: "#fbfbf8",
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 128,
    paddingHorizontal: 18,
    paddingVertical: 18,
    position: "relative",
  },
  sourceSampleCount: {
    alignSelf: "flex-end",
    color: mobileColors.inkMuted,
    fontSize: mobileTypography.size.sm,
    fontWeight: "800",
    lineHeight: 14,
  },
  sourceSampleText: {
    color: "#30302c",
    fontSize: 15,
    lineHeight: mobileTypography.lineHeight.md,
    marginBottom: 14,
  },
  resultHeader: {
    alignItems: "stretch",
    backgroundColor: "#fbfbf8",
    borderBottomColor: mobileColors.border,
    borderBottomWidth: 1,
    gap: 14,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  resultTitleGroup: {
    gap: 6,
  },
  resultTitle: {
    color: mobileColors.ink,
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 20,
  },
  resultSection: {
    borderBottomColor: mobileColors.border,
    borderBottomWidth: 1,
    gap: 10,
    padding: 22,
  },
  resultSectionLast: {
    borderBottomWidth: 0,
  },
  resultTranslation: {
    color: mobileColors.ink,
    fontSize: 17,
    fontWeight: "700",
    lineHeight: 27,
  },
  sentenceCard: {
    gap: 14,
    minWidth: 0,
    paddingBottom: 20,
    position: "relative",
    width: "100%",
    zIndex: 0,
  },
  sentenceCardActive: {
    zIndex: 20,
  },
  sentenceIndex: {
    color: mobileColors.inkMuted,
    fontSize: mobileTypography.size.xs,
    fontWeight: "800",
    lineHeight: 16,
  },
  sentenceList: {
    minWidth: 0,
    width: "100%",
  },
  sentenceTranslation: {
    borderTopColor: "#eeeeea",
    borderTopWidth: 1,
    color: "#4d4d48",
    fontSize: mobileTypography.size.sm,
    lineHeight: 22,
    paddingTop: 10,
  },
  wordDefinitionCard: {
    alignSelf: "stretch",
    gap: 10,
  },
  wordDefinitionPopoverCard: {
    elevation: 12,
    position: "absolute",
    zIndex: 40,
  },
  wordDefinitionContext: {
    color: mobileColors.inkMuted,
    fontSize: mobileTypography.size.sm,
    fontWeight: "700",
    lineHeight: mobileTypography.lineHeight.sm,
  },
  wordDefinitionHeader: {
    alignItems: "baseline",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
  },
  wordDefinitionMeaning: {
    color: mobileColors.ink,
    fontSize: 17,
    fontWeight: "800",
    lineHeight: 24,
  },
  wordDefinitionPartOfSpeech: {
    color: mobileColors.inkMuted,
    fontSize: mobileTypography.size.sm,
    fontWeight: "800",
    lineHeight: 20,
  },
  wordDefinitionSaveButton: {
    alignItems: "center",
    backgroundColor: "#f4f5ff",
    borderColor: "#cfd5eb",
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 42,
    paddingHorizontal: 14,
  },
  wordDefinitionSaveButtonDisabled: {
    backgroundColor: mobileColors.sidebar,
    opacity: 0.72,
  },
  wordDefinitionSaveButtonText: {
    color: mobileColors.primary,
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 20,
  },
  wordDefinitionTerm: {
    color: mobileColors.ink,
    flexShrink: 1,
    fontSize: 19,
    fontWeight: "900",
    lineHeight: mobileTypography.lineHeight.md,
  },
  wordToken: {
    borderRadius: 6,
    marginHorizontal: -2,
    paddingHorizontal: 2,
  },
  wordTokenActive: {
    backgroundColor: mobileColors.sidebarActive,
  },
  wordPopoverDismissLayer: {
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  wordPopoverOverlay: {
    backgroundColor: "transparent",
    flex: 1,
  },
  suggestionChipSaved: {
    backgroundColor: mobileColors.sidebar,
    borderColor: mobileColors.sidebarActive,
    opacity: 1,
  },
  suggestionChipSaving: {
    opacity: 0.64,
  },
  suggestionList: {
    alignItems: "flex-start",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: mobileSpacing.sm,
  },
  translationNoteList: {
    gap: mobileSpacing.md,
  },
});
