import { StyleSheet } from "react-native";
import {
  mobileButtonTokens,
  mobileColors,
  mobileRadius,
  mobileSpacing,
  mobileTypography,
} from "./mobileTokens";

export const appStyles = StyleSheet.create({
  analyzeButton: {
    alignItems: "center",
    backgroundColor: mobileButtonTokens.send.background,
    borderRadius: mobileButtonTokens.size.icon.radius,
    height: mobileButtonTokens.size.icon.height,
    justifyContent: "center",
    minHeight: mobileButtonTokens.size.icon.height,
    minWidth: mobileButtonTokens.size.icon.width,
    width: mobileButtonTokens.size.icon.width,
  },
  analyzeButtonDisabled: {
    backgroundColor: mobileColors.sidebarActive,
  },
  analyzeButtonText: {
    color: mobileButtonTokens.send.foreground,
    fontSize: mobileTypography.size.lg,
    fontWeight: "800",
    lineHeight: 22,
  },
  analyzeButtonTextDisabled: {
    color: mobileColors.inkMuted,
  },
  bottomArea: {
    backgroundColor: "rgba(255, 255, 255, 0.92)",
    borderTopColor: mobileColors.border,
    borderTopWidth: 1,
    gap: 10,
    paddingHorizontal: 14,
    paddingTop: 14,
  },
  brandGroup: {
    alignItems: "center",
    flexDirection: "row",
    gap: 9,
    height: 38,
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  composer: {
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.composer,
    borderWidth: 1,
    gap: 10,
    padding: 14,
    shadowColor: mobileColors.ink,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
  },
  composerWrap: {
    gap: 10,
    marginTop: "auto",
    width: "100%",
  },
  composerFooter: {
    alignItems: "center",
    flexDirection: "row",
    gap: mobileSpacing.md,
    justifyContent: "space-between",
  },
  composerLabel: {
    color: mobileColors.ink,
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 18,
  },
  composerMeta: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    minWidth: 0,
  },
  modelSelectButton: {
    alignItems: "center",
    backgroundColor: mobileColors.surfaceMuted,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
    minHeight: 32,
    paddingHorizontal: 12,
  },
  modelSelectChevron: {
    borderBottomColor: mobileColors.inkMuted,
    borderBottomWidth: 2,
    borderRightColor: mobileColors.inkMuted,
    borderRightWidth: 2,
    height: 7,
    marginTop: -3,
    transform: [{ rotate: "45deg" }],
    width: 7,
  },
  modelSelectText: {
    color: mobileColors.ink,
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 18,
  },
  modelSelectorCard: {
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    gap: 6,
    left: 18,
    padding: 8,
    position: "absolute",
    right: 18,
    shadowColor: mobileColors.ink,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 20,
    top: "34%",
  },
  modelSelectorDismissLayer: {
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  modelSelectorOption: {
    borderRadius: mobileRadius.sm,
    minHeight: 42,
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  modelSelectorOptionActive: {
    backgroundColor: mobileColors.sidebarActive,
  },
  modelSelectorOptionText: {
    color: mobileColors.inkMuted,
    fontSize: 15,
    fontWeight: "700",
    lineHeight: mobileTypography.lineHeight.sm,
  },
  modelSelectorOptionTextActive: {
    color: mobileColors.ink,
  },
  modelSelectorOverlay: {
    backgroundColor: "rgba(32, 32, 29, 0.16)",
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  content: {
    alignItems: "stretch",
    flexGrow: 1,
    gap: 20,
    paddingHorizontal: 14,
    paddingTop: 20,
    paddingBottom: mobileSpacing.xl,
    width: "100%",
  },
  count: {
    color: mobileColors.inkMuted,
    fontSize: 13,
    fontWeight: "400",
    lineHeight: 18,
  },
  inputDisclosure: {
    color: mobileColors.inkMuted,
    fontSize: mobileTypography.size.xs,
    lineHeight: 18,
    width: "100%",
  },
  input: {
    color: mobileColors.ink,
    fontSize: 15,
    lineHeight: 23,
    minHeight: 46,
    outlineColor: "transparent",
    outlineWidth: 0,
    padding: 0,
  },
  inputFocusReset: {
    borderColor: "transparent",
  },
  loginButton: {
    alignItems: "center",
    backgroundColor: mobileColors.surfaceMuted,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    minHeight: 36,
    paddingHorizontal: mobileSpacing.md,
    paddingVertical: mobileSpacing.sm,
  },
  loginButtonDisabled: {
    opacity: 0.64,
  },
  loginButtonText: {
    color: mobileColors.ink,
    fontSize: 13,
    fontWeight: "800",
  },
  logo: {
    color: mobileColors.ink,
    fontSize: 15,
    fontWeight: "800",
  },
  logoMark: {
    alignItems: "center",
    backgroundColor: mobileColors.ink,
    borderRadius: 7,
    height: 24,
    justifyContent: "center",
    width: 24,
  },
  logoMarkText: {
    color: "#fbfbf8",
    fontSize: mobileTypography.size.xs,
    fontWeight: "800",
    lineHeight: 16,
  },
  pressed: {
    opacity: 0.72,
  },
  statusCard: {
    backgroundColor: mobileColors.surfaceMuted,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 96,
    paddingHorizontal: 24,
    paddingVertical: 20,
  },
  statusText: {
    color: mobileColors.inkMuted,
    fontSize: mobileTypography.size.sm,
    lineHeight: 22,
  },
  statusTitle: {
    color: mobileColors.ink,
    fontSize: mobileTypography.size.lg,
    fontWeight: "800",
    lineHeight: 24,
  },
  safeArea: {
    backgroundColor: mobileColors.surface,
    flex: 1,
  },
  screenArea: {
    flex: 1,
  },
  shell: {
    backgroundColor: mobileColors.surface,
    flex: 1,
    position: "relative",
  },
  tabbar: {
    alignItems: "center",
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    flexDirection: "row",
    gap: mobileSpacing.xs,
    marginBottom: mobileSpacing.sm,
    minHeight: 54,
    padding: mobileSpacing.xs,
  },
  tabItem: {
    alignItems: "center",
    borderRadius: 6,
    flex: 1,
    minHeight: 44,
    justifyContent: "center",
  },
  tabItemActive: {
    backgroundColor: mobileColors.sidebar,
  },
  tabItemDisabled: {
    opacity: 0.54,
  },
  tabText: {
    color: mobileColors.inkMuted,
    fontSize: 13,
    fontWeight: "800",
  },
  tabTextActive: {
    color: mobileColors.primary,
  },
  tabTextDisabled: {
    color: mobileColors.inkMuted,
  },
  topbar: {
    alignItems: "center",
    backgroundColor: mobileColors.surface,
    borderBottomColor: mobileColors.border,
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: mobileSpacing.md,
  },
  toast: {
    alignSelf: "center",
    backgroundColor: mobileColors.ink,
    borderRadius: mobileRadius.pill,
    maxWidth: 420,
    paddingHorizontal: mobileSpacing.lg,
    paddingVertical: 11,
    shadowColor: mobileColors.ink,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
  },
  toastOverlay: {
    left: 14,
    position: "absolute",
    right: 14,
    top: 76,
    zIndex: 20,
  },
  toastText: {
    color: mobileColors.primaryInk,
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 18,
    textAlign: "center",
  },
});
