import { StyleSheet } from "react-native";
import { nativeTokens } from "@nado/tokens/react-native";

export const mobileColors = {
  canvas: nativeTokens.color.canvas,
  surface: nativeTokens.color.surface,
  surfaceMuted: nativeTokens.color.surfaceMuted,
  sidebar: nativeTokens.color.sidebar,
  sidebarActive: nativeTokens.color.sidebarActive,
  ink: nativeTokens.color.ink,
  inkMuted: nativeTokens.color.inkMuted,
  border: nativeTokens.color.border,
  primary: nativeTokens.color.primary,
  primaryInk: nativeTokens.color.primaryInk,
} as const;

export const mobileRadius = nativeTokens.radius;
export const mobileSpacing = nativeTokens.spacing;

export const styles = StyleSheet.create({
  analyzeButton: {
    alignItems: "center",
    backgroundColor: mobileColors.primary,
    borderRadius: mobileRadius.pill,
    height: 38,
    justifyContent: "center",
    minHeight: 38,
    minWidth: 38,
    width: 38,
  },
  analyzeButtonDisabled: {
    backgroundColor: mobileColors.sidebarActive,
  },
  analyzeButtonText: {
    color: mobileColors.primaryInk,
    fontSize: 18,
    fontWeight: "800",
    lineHeight: 22,
  },
  analyzeButtonTextDisabled: {
    color: mobileColors.inkMuted,
  },
  analysisResultStack: {
    gap: 24,
  },
  bottomArea: {
    backgroundColor: "rgba(255, 255, 255, 0.92)",
    borderTopColor: mobileColors.border,
    borderTopWidth: 1,
    gap: 10,
    paddingHorizontal: 14,
    paddingTop: 14,
  },
  brandGroup: {
    alignItems: "center",
    flexDirection: "row",
    gap: 9,
    height: 38,
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  cardHeader: {
    alignItems: "stretch",
    gap: 6,
  },
  chunkContent: {
    maxWidth: "100%",
    minWidth: 0,
    position: "relative",
  },
  chunkEnglish: {
    color: mobileColors.ink,
    fontSize: 20,
    fontWeight: "900",
    lineHeight: 28,
  },
  chunkEnglishLine: {
    alignItems: "baseline",
    flexDirection: "row",
    flexWrap: "wrap",
    maxWidth: "100%",
    minWidth: 0,
  },
  chunkSlash: {
    color: "#d33b35",
    fontSize: 24,
    fontWeight: "900",
    lineHeight: 31,
    marginHorizontal: 2,
  },
  chunkUnit: {
    alignItems: "flex-start",
    flexShrink: 1,
    maxWidth: "100%",
    minWidth: 0,
  },
  chunkUnitActive: {
    zIndex: 30,
  },
  chunkKorean: {
    color: mobileColors.inkMuted,
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 19,
  },
  chunkLine: {
    alignItems: "flex-start",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    minWidth: 0,
    width: "100%",
  },
  composer: {
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.composer,
    borderWidth: 1,
    gap: 10,
    padding: 14,
    shadowColor: mobileColors.ink,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
  },
  composerWrap: {
    gap: 10,
    width: "100%",
  },
  composerFooter: {
    alignItems: "center",
    flexDirection: "row",
    gap: mobileSpacing.md,
    justifyContent: "space-between",
  },
  composerLabel: {
    color: mobileColors.ink,
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 18,
  },
  composerMeta: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    minWidth: 0,
  },
  content: {
    alignItems: "stretch",
    gap: 20,
    paddingHorizontal: 14,
    paddingTop: 20,
    paddingBottom: mobileSpacing.xl,
    width: "100%",
  },
  count: {
    color: mobileColors.inkMuted,
    fontSize: 13,
    fontWeight: "400",
    lineHeight: 18,
  },
  emptyText: {
    color: mobileColors.inkMuted,
    fontSize: 15,
    lineHeight: 23,
  },
  emptyPanel: {
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    gap: 8,
    minHeight: 0,
    paddingHorizontal: 20,
    paddingVertical: 18,
  },
  emptyPanelText: {
    color: mobileColors.inkMuted,
    fontSize: 14,
    lineHeight: 22,
  },
  emptyPanelTitle: {
    color: mobileColors.ink,
    fontSize: 16,
    fontWeight: "800",
    lineHeight: 22,
  },
  eyebrow: {
    color: mobileColors.inkMuted,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 16,
    textTransform: "uppercase",
  },
  inputDisclosure: {
    color: mobileColors.inkMuted,
    fontSize: 12,
    lineHeight: 18,
    width: "100%",
  },
  grammarExplanation: {
    color: mobileColors.inkMuted,
    fontSize: 13,
    lineHeight: 20,
    minWidth: 0,
  },
  grammarDescription: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    minWidth: 0,
  },
  grammarItem: {
    alignItems: "baseline",
    flexDirection: "row",
    gap: 12,
    minWidth: 0,
  },
  grammarList: {
    gap: 10,
  },
  grammarTarget: {
    color: mobileColors.ink,
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 20,
    minWidth: 0,
  },
  grammarType: {
    color: mobileColors.inkMuted,
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 20,
  },
  input: {
    color: mobileColors.ink,
    fontSize: 15,
    lineHeight: 23,
    minHeight: 46,
    outlineColor: "transparent",
    outlineWidth: 0,
    padding: 0,
  },
  inputFocusReset: {
    borderColor: "transparent",
  },
  itemFooter: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
    marginTop: "auto",
  },
  itemMeta: {
    color: mobileColors.inkMuted,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 16,
  },
  loginButton: {
    alignItems: "center",
    backgroundColor: mobileColors.surfaceMuted,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    minHeight: 36,
    paddingHorizontal: mobileSpacing.md,
    paddingVertical: mobileSpacing.sm,
  },
  loginButtonDisabled: {
    opacity: 0.64,
  },
  loginButtonText: {
    color: mobileColors.ink,
    fontSize: 13,
    fontWeight: "800",
  },
  logo: {
    color: mobileColors.ink,
    fontSize: 15,
    fontWeight: "800",
  },
  logoMark: {
    alignItems: "center",
    backgroundColor: mobileColors.ink,
    borderRadius: 7,
    height: 24,
    justifyContent: "center",
    width: 24,
  },
  logoMarkText: {
    color: "#fbfbf8",
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 16,
  },
  meaningCard: {
    backgroundColor: mobileColors.surfaceMuted,
    borderColor: "#eeeeea",
    borderRadius: 7,
    borderWidth: 1,
    gap: mobileSpacing.xs,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  meaningNote: {
    color: mobileColors.inkMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  meaningText: {
    color: mobileColors.ink,
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 20,
  },
  meaningList: {
    gap: mobileSpacing.sm,
  },
  noticePanel: {
    backgroundColor: mobileColors.surfaceMuted,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    gap: 6,
    paddingHorizontal: mobileSpacing.lg,
    paddingVertical: 14,
  },
  noticeText: {
    color: mobileColors.inkMuted,
    fontSize: 14,
    lineHeight: 22,
  },
  noticeTitle: {
    color: mobileColors.ink,
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 20,
  },
  noteItem: {
    gap: mobileSpacing.xs,
  },
  noteTerm: {
    color: mobileColors.primary,
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 20,
  },
  noteText: {
    color: mobileColors.ink,
    fontSize: 14,
    lineHeight: 23,
  },
  pageLayout: {
    alignSelf: "stretch",
    gap: 14,
    width: "100%",
  },
  pageHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: mobileSpacing.md,
    justifyContent: "space-between",
  },
  pageStack: {
    alignSelf: "stretch",
    gap: 18,
    width: "100%",
  },
  pageDescription: {
    color: mobileColors.inkMuted,
    fontSize: 14,
    lineHeight: 22,
  },
  pageTitleGroup: {
    gap: 6,
  },
  pageTitle: {
    color: mobileColors.ink,
    fontSize: 24,
    fontWeight: "800",
    lineHeight: 30,
  },
  panelText: {
    color: mobileColors.inkMuted,
    fontSize: 14,
    lineHeight: 22,
  },
  pressed: {
    opacity: 0.72,
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: mobileColors.primary,
    borderRadius: mobileRadius.md,
    justifyContent: "center",
    minHeight: 40,
    paddingHorizontal: mobileSpacing.lg,
  },
  primaryButtonText: {
    color: mobileColors.primaryInk,
    fontSize: 14,
    fontWeight: "800",
    textAlign: "center",
  },
  refreshButton: {
    alignItems: "center",
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  refreshButtonDisabled: {
    opacity: 0.58,
  },
  refreshButtonIcon: {
    color: mobileColors.inkMuted,
    fontSize: 21,
    fontWeight: "700",
    height: 36,
    includeFontPadding: false,
    lineHeight: 36,
    textAlign: "center",
    transform: [{ translateX: -0.5 }, { translateY: -1 }],
    width: 36,
  },
  reviewCard: {
    alignItems: "center",
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    gap: 10,
    justifyContent: "center",
    minHeight: 220,
    paddingHorizontal: 28,
    paddingVertical: 28,
    shadowColor: mobileColors.ink,
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.04,
    shadowRadius: 24,
  },
  reviewActionButton: {
    flex: 1,
    minWidth: 0,
  },
  reviewActions: {
    alignSelf: "stretch",
    flexDirection: "row",
    gap: mobileSpacing.sm,
    minWidth: 0,
    width: "100%",
  },
  reviewAnswer: {
    alignSelf: "stretch",
    backgroundColor: "#f6f8ff",
    borderColor: "#d5dbea",
    borderRadius: 7,
    borderWidth: 1,
    color: mobileColors.inkMuted,
    filter: "blur(5px)",
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 22,
    minHeight: 22,
    padding: 14,
    textAlign: "center",
    userSelect: "none",
  },
  reviewAnswerRevealed: {
    filter: "none",
    userSelect: "auto",
  },
  reviewControls: {
    alignSelf: "stretch",
    flexDirection: "row",
    gap: mobileSpacing.sm,
    minWidth: 0,
    width: "100%",
  },
  reviewDirection: {
    alignItems: "center",
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    minHeight: 36,
    minWidth: 0,
    paddingHorizontal: 12,
  },
  reviewDirectionActive: {
    backgroundColor: mobileColors.sidebarActive,
    borderColor: mobileColors.border,
  },
  reviewDirectionText: {
    color: mobileColors.inkMuted,
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 36,
  },
  reviewDirectionTextActive: {
    color: mobileColors.ink,
  },
  reviewTerm: {
    color: mobileColors.ink,
    fontSize: 28,
    fontWeight: "800",
    lineHeight: 36,
    textAlign: "center",
  },
  reviewMeta: {
    color: mobileColors.inkMuted,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 16,
  },
  reviewNote: {
    color: mobileColors.inkMuted,
    fontSize: 14,
    lineHeight: 22,
    maxWidth: 420,
    textAlign: "center",
  },
  resultArea: {
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    gap: 0,
    overflow: "hidden",
    padding: 0,
  },
  sourceSample: {
    backgroundColor: "#fbfbf8",
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 128,
    paddingHorizontal: 18,
    paddingVertical: 18,
    position: "relative",
  },
  sourceSampleCount: {
    alignSelf: "flex-end",
    color: mobileColors.inkMuted,
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 14,
  },
  sourceSampleText: {
    color: "#30302c",
    fontSize: 15,
    lineHeight: 26,
    marginBottom: 14,
  },
  resultHeader: {
    alignItems: "stretch",
    backgroundColor: "#fbfbf8",
    borderBottomColor: mobileColors.border,
    borderBottomWidth: 1,
    gap: 14,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  resultTitleGroup: {
    gap: 6,
  },
  resultTitle: {
    color: mobileColors.ink,
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 20,
  },
  resultSection: {
    borderBottomColor: mobileColors.border,
    borderBottomWidth: 1,
    gap: 10,
    padding: 22,
  },
  resultSectionLast: {
    borderBottomWidth: 0,
  },
  resultTranslation: {
    color: mobileColors.ink,
    fontSize: 17,
    fontWeight: "700",
    lineHeight: 27,
  },
  statusCard: {
    backgroundColor: mobileColors.surfaceMuted,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 96,
    paddingHorizontal: 24,
    paddingVertical: 20,
  },
  statusText: {
    color: mobileColors.inkMuted,
    fontSize: 14,
    lineHeight: 22,
  },
  statusTitle: {
    color: mobileColors.ink,
    fontSize: 18,
    fontWeight: "800",
    lineHeight: 24,
  },
  sentenceCard: {
    gap: 14,
    minWidth: 0,
    paddingBottom: 20,
    position: "relative",
    width: "100%",
    zIndex: 0,
  },
  sentenceCardActive: {
    zIndex: 20,
  },
  sentenceIndex: {
    color: mobileColors.inkMuted,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 16,
  },
  sentenceList: {
    minWidth: 0,
    width: "100%",
  },
  sentenceTranslation: {
    borderTopColor: "#eeeeea",
    borderTopWidth: 1,
    color: "#4d4d48",
    fontSize: 14,
    lineHeight: 22,
    paddingTop: 10,
  },
  wordDefinitionCard: {
    alignSelf: "stretch",
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    elevation: 4,
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 14,
    shadowColor: mobileColors.ink,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
  },
  wordDefinitionPopoverCard: {
    elevation: 12,
    position: "absolute",
    zIndex: 40,
  },
  wordDefinitionContext: {
    color: mobileColors.inkMuted,
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 21,
  },
  wordDefinitionHeader: {
    alignItems: "baseline",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
  },
  wordDefinitionMeaning: {
    color: mobileColors.ink,
    fontSize: 17,
    fontWeight: "800",
    lineHeight: 24,
  },
  wordDefinitionPartOfSpeech: {
    color: mobileColors.inkMuted,
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 20,
  },
  wordDefinitionSaveButton: {
    alignItems: "center",
    backgroundColor: "#f4f5ff",
    borderColor: "#cfd5eb",
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 42,
    paddingHorizontal: 14,
  },
  wordDefinitionSaveButtonDisabled: {
    backgroundColor: mobileColors.sidebar,
    opacity: 0.72,
  },
  wordDefinitionSaveButtonText: {
    color: mobileColors.primary,
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 20,
  },
  wordDefinitionTerm: {
    color: mobileColors.ink,
    flexShrink: 1,
    fontSize: 19,
    fontWeight: "900",
    lineHeight: 26,
  },
  wordToken: {
    borderRadius: 6,
    marginHorizontal: -2,
    paddingHorizontal: 2,
  },
  wordTokenActive: {
    backgroundColor: mobileColors.sidebarActive,
  },
  wordPopoverDismissLayer: {
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  wordPopoverOverlay: {
    backgroundColor: "transparent",
    flex: 1,
  },
  suggestionChip: {
    alignItems: "flex-start",
    alignSelf: "flex-start",
    backgroundColor: mobileColors.surfaceMuted,
    borderColor: "#d8d8d2",
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    maxWidth: "100%",
    minHeight: 34,
    minWidth: 0,
    paddingHorizontal: mobileSpacing.md,
    paddingVertical: 7,
  },
  suggestionChipSaved: {
    backgroundColor: mobileColors.sidebar,
    borderColor: mobileColors.sidebarActive,
  },
  suggestionChipSaving: {
    opacity: 0.64,
  },
  suggestionList: {
    alignItems: "flex-start",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: mobileSpacing.sm,
  },
  suggestionPrefix: {
    color: mobileColors.primary,
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 18,
  },
  suggestionText: {
    color: mobileColors.primary,
    flexShrink: 1,
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 18,
    minWidth: 0,
  },
  translationNoteList: {
    gap: mobileSpacing.md,
  },
  safeArea: {
    backgroundColor: mobileColors.surface,
    flex: 1,
  },
  shell: {
    backgroundColor: mobileColors.surface,
    flex: 1,
    position: "relative",
  },
  sectionHeader: {
    alignItems: "flex-start",
    gap: mobileSpacing.sm,
  },
  sectionMeta: {
    color: mobileColors.inkMuted,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 18,
  },
  sectionTitle: {
    color: mobileColors.ink,
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 21,
  },
  sectionTitleGroup: {
    gap: 5,
  },
  summaryItem: {
    alignItems: "center",
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    flexDirection: "row",
    gap: mobileSpacing.sm,
    justifyContent: "space-between",
    minHeight: 66,
    paddingHorizontal: mobileSpacing.lg,
    paddingVertical: 14,
  },
  summaryLabel: {
    color: mobileColors.inkMuted,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 16,
  },
  summaryValue: {
    color: mobileColors.ink,
    fontSize: 20,
    fontWeight: "800",
    lineHeight: 20,
  },
  tabbar: {
    alignItems: "center",
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    flexDirection: "row",
    gap: mobileSpacing.xs,
    marginBottom: mobileSpacing.sm,
    minHeight: 54,
    padding: mobileSpacing.xs,
  },
  tabItem: {
    alignItems: "center",
    borderRadius: 6,
    flex: 1,
    minHeight: 44,
    justifyContent: "center",
  },
  tabItemActive: {
    backgroundColor: mobileColors.sidebar,
  },
  tabItemDisabled: {
    opacity: 0.54,
  },
  tabText: {
    color: mobileColors.inkMuted,
    fontSize: 13,
    fontWeight: "800",
  },
  tabTextActive: {
    color: mobileColors.primary,
  },
  tabTextDisabled: {
    color: mobileColors.inkMuted,
  },
  termGroup: {
    flex: 1,
    gap: mobileSpacing.xs,
    minWidth: 0,
  },
  termText: {
    color: mobileColors.ink,
    fontSize: 16,
    fontWeight: "800",
    lineHeight: 22,
  },
  topbar: {
    alignItems: "center",
    backgroundColor: mobileColors.surface,
    borderBottomColor: mobileColors.border,
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: mobileSpacing.md,
  },
  toast: {
    alignSelf: "center",
    backgroundColor: mobileColors.ink,
    borderRadius: mobileRadius.pill,
    maxWidth: 420,
    paddingHorizontal: mobileSpacing.lg,
    paddingVertical: 11,
    shadowColor: mobileColors.ink,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
  },
  toastOverlay: {
    left: 14,
    position: "absolute",
    right: 14,
    top: 76,
    zIndex: 20,
  },
  toastText: {
    color: mobileColors.primaryInk,
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 18,
    textAlign: "center",
  },
  vocabularyItem: {
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    gap: 14,
    minHeight: 220,
    padding: 18,
    shadowColor: mobileColors.ink,
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.04,
    shadowRadius: 24,
  },
  vocabularyListWrap: {
    gap: mobileSpacing.md,
  },
  vocabularyType: {
    alignSelf: "flex-start",
    backgroundColor: mobileColors.surfaceMuted,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.pill,
    borderWidth: 1,
    color: mobileColors.inkMuted,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 12,
    paddingHorizontal: mobileSpacing.sm,
    paddingVertical: 5,
  },
  secondaryButton: {
    alignItems: "center",
    backgroundColor: mobileColors.surfaceMuted,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 32,
    paddingHorizontal: mobileSpacing.md,
  },
  secondaryButtonText: {
    color: mobileColors.ink,
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 32,
    textAlign: "center",
  },
});
