import { StyleSheet } from "react-native";
import { nativeTokens } from "@nado/tokens/react-native";

export const mobileColors = {
  canvas: nativeTokens.color.canvas,
  surface: nativeTokens.color.surface,
  surfaceMuted: nativeTokens.color.surfaceMuted,
  sidebar: nativeTokens.color.sidebar,
  sidebarActive: nativeTokens.color.sidebarActive,
  ink: nativeTokens.color.ink,
  inkMuted: nativeTokens.color.inkMuted,
  border: nativeTokens.color.border,
  primary: nativeTokens.color.primary,
  primaryInk: nativeTokens.color.primaryInk,
} as const;

export const mobileRadius = nativeTokens.radius;
export const mobileSpacing = nativeTokens.spacing;

export const styles = StyleSheet.create({
  analyzeButton: {
    alignItems: "center",
    backgroundColor: mobileColors.primary,
    borderRadius: mobileRadius.md,
    minHeight: 42,
    minWidth: 74,
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  analyzeButtonDisabled: {
    backgroundColor: mobileColors.sidebarActive,
  },
  analyzeButtonText: {
    color: mobileColors.primaryInk,
    fontSize: 15,
    fontWeight: "800",
  },
  analyzeButtonTextDisabled: {
    color: mobileColors.inkMuted,
  },
  bottomArea: {
    backgroundColor: "rgba(255, 255, 255, 0.92)",
    borderTopColor: mobileColors.border,
    borderTopWidth: 1,
    gap: 10,
    paddingHorizontal: 14,
    paddingTop: 14,
  },
  brandGroup: {
    height: 38,
    justifyContent: "center",
  },
  cardHeader: {
    alignItems: "stretch",
    gap: 6,
  },
  chunkContent: {
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    gap: 5,
    minWidth: 0,
    paddingHorizontal: mobileSpacing.md,
    paddingVertical: 10,
    width: "100%",
  },
  chunkEnglish: {
    color: mobileColors.ink,
    fontSize: 16,
    fontWeight: "800",
    lineHeight: 22,
  },
  chunkUnit: {
    alignItems: "flex-start",
    minWidth: 0,
    width: "100%",
  },
  chunkKorean: {
    color: mobileColors.inkMuted,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 17,
    width: "100%",
  },
  chunkLine: {
    gap: mobileSpacing.sm,
    minWidth: 0,
    width: "100%",
  },
  composer: {
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.composer,
    borderWidth: 1,
    gap: 10,
    padding: 14,
    shadowColor: mobileColors.ink,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
  },
  composerFooter: {
    alignItems: "center",
    flexDirection: "row",
    gap: mobileSpacing.md,
    justifyContent: "space-between",
  },
  content: {
    alignItems: "stretch",
    gap: 20,
    paddingHorizontal: 14,
    paddingTop: 20,
    paddingBottom: mobileSpacing.xl,
    width: "100%",
  },
  count: {
    color: mobileColors.inkMuted,
    fontSize: 13,
    fontWeight: "700",
  },
  emptyText: {
    color: mobileColors.inkMuted,
    fontSize: 15,
    lineHeight: 23,
  },
  emptyPanel: {
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    gap: 8,
    minHeight: 0,
    paddingHorizontal: 20,
    paddingVertical: 18,
  },
  emptyPanelText: {
    color: mobileColors.inkMuted,
    fontSize: 14,
    lineHeight: 22,
  },
  emptyPanelTitle: {
    color: mobileColors.ink,
    fontSize: 16,
    fontWeight: "800",
    lineHeight: 22,
  },
  eyebrow: {
    color: mobileColors.inkMuted,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 16,
    textTransform: "uppercase",
  },
  helperText: {
    color: mobileColors.inkMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  grammarExplanation: {
    color: mobileColors.inkMuted,
    fontSize: 13,
    lineHeight: 20,
    minWidth: 0,
  },
  grammarItem: {
    alignItems: "flex-start",
    borderTopColor: mobileColors.border,
    borderTopWidth: 1,
    gap: mobileSpacing.sm,
    paddingTop: 10,
  },
  grammarList: {
    gap: 10,
  },
  grammarTarget: {
    color: mobileColors.ink,
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 20,
  },
  grammarType: {
    color: mobileColors.inkMuted,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 20,
  },
  input: {
    color: mobileColors.ink,
    fontSize: 15,
    lineHeight: 22,
    minHeight: 74,
    outlineColor: "transparent",
    outlineWidth: 0,
    padding: 0,
  },
  inputFocusReset: {
    borderColor: "transparent",
  },
  itemFooter: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
    marginTop: "auto",
  },
  itemMeta: {
    color: mobileColors.inkMuted,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 16,
  },
  loginButton: {
    alignItems: "center",
    backgroundColor: mobileColors.surfaceMuted,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    minHeight: 36,
    paddingHorizontal: mobileSpacing.md,
    paddingVertical: mobileSpacing.sm,
  },
  loginButtonDisabled: {
    opacity: 0.64,
  },
  loginButtonText: {
    color: mobileColors.ink,
    fontSize: 13,
    fontWeight: "800",
  },
  logo: {
    color: mobileColors.ink,
    fontSize: 15,
    fontWeight: "800",
  },
  meaningCard: {
    backgroundColor: mobileColors.surfaceMuted,
    borderColor: "#eeeeea",
    borderRadius: 7,
    borderWidth: 1,
    gap: mobileSpacing.xs,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  meaningNote: {
    color: mobileColors.inkMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  meaningText: {
    color: mobileColors.ink,
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 20,
  },
  meaningList: {
    gap: mobileSpacing.sm,
  },
  noticePanel: {
    backgroundColor: mobileColors.surfaceMuted,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    gap: 6,
    paddingHorizontal: mobileSpacing.lg,
    paddingVertical: 14,
  },
  noticeText: {
    color: mobileColors.inkMuted,
    fontSize: 14,
    lineHeight: 22,
  },
  noticeTitle: {
    color: mobileColors.ink,
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 20,
  },
  noteItem: {
    gap: mobileSpacing.xs,
  },
  noteTerm: {
    color: mobileColors.primary,
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 20,
  },
  noteText: {
    color: mobileColors.ink,
    fontSize: 14,
    lineHeight: 22,
  },
  pageLayout: {
    alignSelf: "stretch",
    gap: 14,
    width: "100%",
  },
  pageHeader: {
    alignItems: "stretch",
    gap: mobileSpacing.sm,
  },
  pageStack: {
    alignSelf: "stretch",
    gap: 18,
    width: "100%",
  },
  pageDescription: {
    color: mobileColors.inkMuted,
    fontSize: 14,
    lineHeight: 22,
  },
  pageTitleGroup: {
    gap: 6,
  },
  pageTitle: {
    color: mobileColors.ink,
    fontSize: 24,
    fontWeight: "800",
    lineHeight: 30,
  },
  panelText: {
    color: mobileColors.inkMuted,
    fontSize: 14,
    lineHeight: 22,
  },
  pressed: {
    opacity: 0.72,
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: mobileColors.primary,
    borderRadius: mobileRadius.md,
    justifyContent: "center",
    minHeight: 40,
    paddingHorizontal: mobileSpacing.lg,
  },
  primaryButtonText: {
    color: mobileColors.primaryInk,
    fontSize: 14,
    fontWeight: "800",
    textAlign: "center",
  },
  reviewCard: {
    alignItems: "center",
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    gap: 10,
    justifyContent: "center",
    minHeight: 220,
    paddingHorizontal: 28,
    paddingVertical: 28,
    shadowColor: mobileColors.ink,
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.04,
    shadowRadius: 24,
  },
  reviewActionButton: {
    flex: 1,
    minWidth: 0,
  },
  reviewActions: {
    alignSelf: "stretch",
    flexDirection: "row",
    gap: mobileSpacing.sm,
    minWidth: 0,
    width: "100%",
  },
  reviewAnswer: {
    color: mobileColors.inkMuted,
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 22,
    minHeight: 22,
  },
  reviewAnswerHidden: {
    color: "transparent",
    textShadowColor: mobileColors.inkMuted,
    textShadowOffset: { height: 0, width: 0 },
    textShadowRadius: 6,
  },
  reviewControls: {
    alignSelf: "stretch",
    flexDirection: "row",
    gap: mobileSpacing.sm,
    minWidth: 0,
    width: "100%",
  },
  reviewDirection: {
    alignItems: "center",
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    minHeight: 36,
    minWidth: 0,
    paddingHorizontal: 12,
  },
  reviewDirectionActive: {
    backgroundColor: mobileColors.sidebarActive,
    borderColor: mobileColors.border,
  },
  reviewDirectionText: {
    color: mobileColors.inkMuted,
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 36,
  },
  reviewDirectionTextActive: {
    color: mobileColors.ink,
  },
  reviewTerm: {
    color: mobileColors.ink,
    fontSize: 28,
    fontWeight: "800",
    lineHeight: 36,
    textAlign: "center",
  },
  reviewMeta: {
    color: mobileColors.inkMuted,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 16,
  },
  reviewNote: {
    color: mobileColors.inkMuted,
    fontSize: 14,
    lineHeight: 22,
    maxWidth: 420,
    textAlign: "center",
  },
  resultArea: {
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    gap: 0,
    padding: 0,
  },
  sourceSample: {
    backgroundColor: mobileColors.surfaceMuted,
    borderBottomColor: mobileColors.border,
    borderBottomWidth: 1,
    justifyContent: "center",
    minHeight: 128,
    paddingBottom: 36,
    paddingHorizontal: 18,
    paddingTop: mobileSpacing.xl,
    position: "relative",
  },
  sourceSampleCount: {
    bottom: 16,
    color: mobileColors.inkMuted,
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 14,
    position: "absolute",
    right: 18,
  },
  sourceSampleText: {
    color: mobileColors.ink,
    fontSize: 15,
    lineHeight: 24,
  },
  resultDescription: {
    color: mobileColors.inkMuted,
    fontSize: 13,
    lineHeight: 20,
  },
  resultHeader: {
    alignItems: "flex-start",
    borderBottomColor: mobileColors.border,
    borderBottomWidth: 1,
    gap: mobileSpacing.sm,
    paddingHorizontal: 18,
    paddingVertical: mobileSpacing.lg,
  },
  resultTitleGroup: {
    gap: 6,
  },
  resultTitle: {
    color: mobileColors.ink,
    fontSize: 18,
    fontWeight: "800",
    lineHeight: 24,
  },
  resultMeta: {
    color: mobileColors.inkMuted,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 16,
  },
  resultSection: {
    borderBottomColor: mobileColors.border,
    borderBottomWidth: 1,
    gap: mobileSpacing.md,
    paddingHorizontal: 18,
    paddingVertical: 18,
  },
  resultTranslation: {
    color: mobileColors.ink,
    fontSize: 18,
    fontWeight: "800",
    lineHeight: 28,
  },
  statusCard: {
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    gap: mobileSpacing.sm,
    marginTop: mobileSpacing.sm,
    paddingHorizontal: 18,
    paddingVertical: 18,
    shadowColor: mobileColors.ink,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.04,
    shadowRadius: 18,
  },
  statusText: {
    color: mobileColors.inkMuted,
    fontSize: 14,
    lineHeight: 21,
  },
  statusTitle: {
    color: mobileColors.ink,
    fontSize: 18,
    fontWeight: "800",
    lineHeight: 24,
  },
  sentenceCard: {
    backgroundColor: mobileColors.surfaceMuted,
    borderColor: "#eeeeea",
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    gap: mobileSpacing.md,
    minWidth: 0,
    padding: 14,
    width: "100%",
  },
  sentenceIndex: {
    color: mobileColors.inkMuted,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 16,
  },
  sentenceList: {
    gap: mobileSpacing.md,
    minWidth: 0,
    width: "100%",
  },
  sentenceTranslation: {
    color: mobileColors.ink,
    fontSize: 14,
    lineHeight: 22,
  },
  suggestionChip: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: mobileColors.surfaceMuted,
    borderColor: "#d8d8d2",
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    minHeight: 34,
    paddingHorizontal: mobileSpacing.md,
    paddingVertical: 7,
  },
  suggestionChipSaved: {
    backgroundColor: mobileColors.sidebar,
    borderColor: mobileColors.sidebarActive,
  },
  suggestionChipSaving: {
    opacity: 0.64,
  },
  suggestionList: {
    alignItems: "flex-start",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: mobileSpacing.sm,
  },
  suggestionPrefix: {
    color: mobileColors.primary,
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 18,
  },
  suggestionText: {
    color: mobileColors.primary,
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 18,
  },
  translationNoteList: {
    gap: mobileSpacing.md,
  },
  safeArea: {
    backgroundColor: mobileColors.surface,
    flex: 1,
  },
  shell: {
    backgroundColor: mobileColors.surface,
    flex: 1,
    position: "relative",
  },
  sectionHeader: {
    alignItems: "flex-start",
    gap: mobileSpacing.sm,
  },
  sectionMeta: {
    color: mobileColors.inkMuted,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 18,
  },
  sectionTitle: {
    color: mobileColors.ink,
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 21,
  },
  sectionTitleGroup: {
    gap: 5,
  },
  summaryItem: {
    alignItems: "center",
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    flexDirection: "row",
    gap: mobileSpacing.sm,
    justifyContent: "space-between",
    minHeight: 66,
    paddingHorizontal: mobileSpacing.lg,
    paddingVertical: 14,
  },
  summaryLabel: {
    color: mobileColors.inkMuted,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 16,
  },
  summaryValue: {
    color: mobileColors.ink,
    fontSize: 20,
    fontWeight: "800",
    lineHeight: 20,
  },
  tabbar: {
    alignItems: "center",
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    flexDirection: "row",
    gap: mobileSpacing.xs,
    marginBottom: mobileSpacing.sm,
    minHeight: 54,
    padding: mobileSpacing.xs,
  },
  tabItem: {
    alignItems: "center",
    borderRadius: 6,
    flex: 1,
    minHeight: 44,
    justifyContent: "center",
  },
  tabItemActive: {
    backgroundColor: mobileColors.sidebar,
  },
  tabItemDisabled: {
    opacity: 0.54,
  },
  tabText: {
    color: mobileColors.inkMuted,
    fontSize: 13,
    fontWeight: "800",
  },
  tabTextActive: {
    color: mobileColors.primary,
  },
  tabTextDisabled: {
    color: mobileColors.inkMuted,
  },
  termGroup: {
    flex: 1,
    gap: mobileSpacing.xs,
    minWidth: 0,
  },
  termText: {
    color: mobileColors.ink,
    fontSize: 16,
    fontWeight: "800",
    lineHeight: 22,
  },
  topbar: {
    alignItems: "center",
    backgroundColor: mobileColors.surface,
    borderBottomColor: mobileColors.border,
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: mobileSpacing.md,
  },
  toast: {
    alignSelf: "center",
    backgroundColor: mobileColors.ink,
    borderRadius: mobileRadius.pill,
    maxWidth: 420,
    paddingHorizontal: mobileSpacing.lg,
    paddingVertical: 11,
    shadowColor: mobileColors.ink,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
  },
  toastOverlay: {
    left: 14,
    position: "absolute",
    right: 14,
    top: 76,
    zIndex: 20,
  },
  toastText: {
    color: mobileColors.primaryInk,
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 18,
    textAlign: "center",
  },
  vocabularyItem: {
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    gap: 14,
    minHeight: 220,
    padding: 18,
    shadowColor: mobileColors.ink,
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.04,
    shadowRadius: 24,
  },
  vocabularyListWrap: {
    gap: mobileSpacing.md,
  },
  vocabularyType: {
    alignSelf: "flex-start",
    backgroundColor: mobileColors.surfaceMuted,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.pill,
    borderWidth: 1,
    color: mobileColors.inkMuted,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 12,
    paddingHorizontal: mobileSpacing.sm,
    paddingVertical: 5,
  },
  secondaryButton: {
    alignItems: "center",
    backgroundColor: mobileColors.surfaceMuted,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 32,
    paddingHorizontal: mobileSpacing.md,
  },
  secondaryButtonText: {
    color: mobileColors.ink,
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 32,
    textAlign: "center",
  },
});
