import { StyleSheet } from "react-native";
import {
  mobileButtonTokens,
  mobileColors,
  mobileRadius,
  mobileReviewCardTokens,
  mobileSpacing,
  mobileTypography,
} from "./mobileTokens";

export const studyStyles = StyleSheet.create({
  cardHeader: {
    alignItems: "stretch",
    gap: 6,
  },
  emptyText: {
    color: mobileColors.inkMuted,
    fontSize: 15,
    lineHeight: 23,
  },
  emptyPanel: {
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    gap: 8,
    minHeight: 0,
    paddingHorizontal: 20,
    paddingVertical: 18,
  },
  emptyPanelText: {
    color: mobileColors.inkMuted,
    fontSize: mobileTypography.size.sm,
    lineHeight: 22,
  },
  emptyPanelTitle: {
    color: mobileColors.ink,
    fontSize: mobileTypography.size.md,
    fontWeight: "800",
    lineHeight: 22,
  },
  eyebrow: {
    color: mobileColors.inkMuted,
    fontSize: mobileTypography.size.xs,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 16,
    textTransform: "uppercase",
  },
  itemFooter: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
    marginTop: "auto",
  },
  itemMeta: {
    color: mobileColors.inkMuted,
    fontSize: mobileTypography.size.xs,
    fontWeight: "800",
    lineHeight: 16,
  },
  meaningCard: {
    gap: mobileSpacing.xs,
  },
  meaningNote: {
    color: mobileColors.inkMuted,
    fontSize: mobileTypography.size.xs,
    lineHeight: 18,
  },
  meaningText: {
    color: mobileColors.ink,
    fontSize: mobileTypography.size.sm,
    fontWeight: "800",
    lineHeight: 20,
  },
  meaningList: {
    gap: mobileSpacing.sm,
  },
  pageLayout: {
    alignSelf: "stretch",
    gap: 14,
    width: "100%",
  },
  pageHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: mobileSpacing.md,
    justifyContent: "space-between",
  },
  pageStack: {
    alignSelf: "stretch",
    gap: 18,
    width: "100%",
  },
  pageDescription: {
    color: mobileColors.inkMuted,
    fontSize: mobileTypography.size.sm,
    lineHeight: 22,
  },
  pageTitleGroup: {
    gap: 6,
  },
  pageTitle: {
    color: mobileColors.ink,
    fontSize: 24,
    fontWeight: "800",
    lineHeight: 30,
  },
  panelText: {
    color: mobileColors.inkMuted,
    fontSize: mobileTypography.size.sm,
    lineHeight: 22,
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: mobileButtonTokens.primary.background,
    borderRadius: mobileButtonTokens.radius,
    justifyContent: "center",
    minHeight: mobileButtonTokens.size.md.height,
    paddingHorizontal: mobileButtonTokens.size.md.paddingX,
  },
  primaryButtonText: {
    color: mobileButtonTokens.primary.foreground,
    fontSize: mobileTypography.size.sm,
    fontWeight: "800",
    textAlign: "center",
  },
  refreshButton: {
    alignItems: "center",
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  refreshButtonDisabled: {
    opacity: 0.58,
  },
  refreshButtonIcon: {
    color: mobileColors.inkMuted,
    fontSize: 21,
    fontWeight: "700",
    height: 36,
    includeFontPadding: false,
    lineHeight: 36,
    textAlign: "center",
    transform: [{ translateX: -0.5 }, { translateY: -1 }],
    width: 36,
  },
  reviewCard: {
    alignItems: "center",
    gap: 10,
    justifyContent: "center",
    minHeight: 220,
  },
  reviewActionButton: {
    flex: 1,
    minWidth: 0,
  },
  reviewActions: {
    alignSelf: "stretch",
    flexDirection: "row",
    gap: mobileSpacing.sm,
    minWidth: 0,
    width: "100%",
  },
  reviewAnswer: {
    alignSelf: "stretch",
    backgroundColor: mobileReviewCardTokens.answer.background,
    borderColor: mobileReviewCardTokens.answer.border,
    borderRadius: mobileReviewCardTokens.answer.radius,
    borderWidth: 1,
    color: mobileReviewCardTokens.answer.foreground,
    filter: "blur(5px)",
    fontSize: mobileTypography.size.sm,
    fontWeight: "800",
    lineHeight: 22,
    minHeight: 22,
    padding: mobileReviewCardTokens.answer.padding,
    textAlign: "center",
    userSelect: "none",
  },
  reviewAnswerRevealed: {
    filter: "none",
    userSelect: "auto",
  },
  reviewControls: {
    alignSelf: "stretch",
    flexDirection: "row",
    gap: mobileSpacing.sm,
    minWidth: 0,
    width: "100%",
  },
  reviewDirection: {
    alignItems: "center",
    backgroundColor: mobileColors.surface,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    minHeight: 36,
    minWidth: 0,
    paddingHorizontal: 12,
  },
  reviewDirectionActive: {
    backgroundColor: mobileColors.sidebarActive,
    borderColor: mobileColors.border,
  },
  reviewDirectionText: {
    color: mobileColors.inkMuted,
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 36,
  },
  reviewDirectionTextActive: {
    color: mobileColors.ink,
  },
  reviewTerm: {
    color: mobileColors.ink,
    fontSize: 28,
    fontWeight: "800",
    lineHeight: 36,
    textAlign: "center",
  },
  reviewMeta: {
    color: mobileColors.inkMuted,
    fontSize: mobileTypography.size.xs,
    fontWeight: "800",
    lineHeight: 16,
  },
  reviewNote: {
    color: mobileColors.inkMuted,
    fontSize: mobileTypography.size.sm,
    lineHeight: 22,
    maxWidth: 420,
    textAlign: "center",
  },
  sectionHeader: {
    alignItems: "flex-start",
    gap: mobileSpacing.sm,
  },
  sectionMeta: {
    color: mobileColors.inkMuted,
    fontSize: mobileTypography.size.xs,
    fontWeight: "800",
    lineHeight: 18,
  },
  sectionTitle: {
    color: mobileColors.ink,
    fontSize: 15,
    fontWeight: "800",
    lineHeight: mobileTypography.lineHeight.sm,
  },
  sectionTitleGroup: {
    gap: 5,
  },
  summaryItem: {
    alignItems: "center",
    flexDirection: "row",
    gap: mobileSpacing.sm,
    justifyContent: "space-between",
    minHeight: 66,
  },
  summaryLabel: {
    color: mobileColors.inkMuted,
    fontSize: mobileTypography.size.xs,
    fontWeight: "800",
    lineHeight: 16,
  },
  summaryValue: {
    color: mobileColors.ink,
    fontSize: 20,
    fontWeight: "800",
    lineHeight: 20,
  },
  termGroup: {
    flex: 1,
    gap: mobileSpacing.xs,
    minWidth: 0,
  },
  termText: {
    color: mobileColors.ink,
    fontSize: mobileTypography.size.md,
    fontWeight: "800",
    lineHeight: 22,
  },
  vocabularyItem: {
    gap: 14,
    minHeight: 220,
  },
  vocabularyItemSeparator: {
    height: mobileSpacing.md,
  },
  vocabularyListHeader: {
    gap: 18,
    marginBottom: mobileSpacing.md,
    width: "100%",
  },
  vocabularyListWrap: {
    gap: mobileSpacing.md,
  },
  secondaryButton: {
    alignItems: "center",
    backgroundColor: mobileColors.surfaceMuted,
    borderColor: mobileColors.border,
    borderRadius: mobileRadius.md,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 32,
    paddingHorizontal: mobileSpacing.md,
  },
  secondaryButtonText: {
    color: mobileColors.ink,
    fontSize: 13,
    fontWeight: "800",
    lineHeight: mobileTypography.lineHeight.xl,
    textAlign: "center",
  },
});
